# Generated by Django 5.2.5 on 2025-09-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', '입고'), ('OUT', '출고')], max_length=3, verbose_name='구분')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '재고 이동 기록',
                'verbose_name_plural': '재고 이동 기록',
            },
        ),
    ]
