# Generated by Django 5.2.5 on 2025-10-21 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_product_pallet_quantity_product_products_per_pallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50, verbose_name='구역명 (예: A구역)')),
                ('name', models.CharField(max_length=100, verbose_name='위치명 (예: A-01)')),
                ('max_floor', models.PositiveIntegerField(default=1, verbose_name='최대 층수')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.center', verbose_name='소속 센터')),
            ],
            options={
                'verbose_name': '재고 위치',
                'verbose_name_plural': '재고 위치',
                'unique_together': {('center', 'zone', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', '입고'), ('OUT', '출고')], max_length=3, verbose_name='구분')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='층')),
                ('box_size', models.CharField(blank=True, choices=[('S', '소형'), ('M', '중형'), ('L', '대형'), ('XL', '특대형')], max_length=10, null=True, verbose_name='박스 크기')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.location', verbose_name='위치')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '재고 이동 기록',
                'verbose_name_plural': '재고 이동 기록',
            },
        ),
    ]
