# Generated by Django 5.2.5 on 2025-09-24 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_pallet_quantity_product_products_per_pallet'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='위치명 (예: A-1-1)')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.center', verbose_name='소속 센터')),
            ],
            options={
                'verbose_name': '재고 위치',
                'verbose_name_plural': '재고 위치',
                'unique_together': {('center', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.location', verbose_name='위치'),
        ),
    ]
