# Generated by Django 5.2.5 on 2025-09-24 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_pallet_quantity_product_products_per_pallet'),
        ('stock', '0002_location_stockmovement_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='location',
            name='height',
            field=models.FloatField(default=0, verbose_name='높이 (%)'),
        ),
        migrations.AddField(
            model_name='location',
            name='width',
            field=models.FloatField(default=0, verbose_name='너비 (%)'),
        ),
        migrations.AddField(
            model_name='location',
            name='x_coord',
            field=models.FloatField(default=0, verbose_name='X 좌표 (%)'),
        ),
        migrations.AddField(
            model_name='location',
            name='y_coord',
            field=models.FloatField(default=0, verbose_name='Y 좌표 (%)'),
        ),
        migrations.CreateModel(
            name='WarehouseLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='도면명 (예: 1층 A구역)')),
                ('image', models.ImageField(upload_to='layouts/', verbose_name='도면 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.center', verbose_name='소속 센터')),
            ],
            options={
                'verbose_name': '창고 도면',
                'verbose_name_plural': '창고 도면',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouselayout', verbose_name='소속 도면'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='center',
        ),
    ]
