# Generated by Django 5.2.5 on 2025-09-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_location_unique_together_location_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='box_size',
            field=models.CharField(blank=True, choices=[('S', '소형'), ('M', '중형'), ('L', '대형'), ('XL', '특대형')], max_length=10, null=True, verbose_name='박스 크기'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='층'),
        ),
    ]
