# Generated by Django 5.2.5 on 2025-09-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='센터명')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
            ],
            options={
                'verbose_name': '센터',
                'verbose_name_plural': '센터',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='택배사명')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='연락처')),
            ],
            options={
                'verbose_name': '택배사',
                'verbose_name_plural': '택배사',
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='판매 채널명')),
            ],
            options={
                'verbose_name': '판매 채널',
                'verbose_name_plural': '판매 채널',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='화주사명')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='담당자')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.center', verbose_name='소속 센터')),
            ],
            options={
                'verbose_name': '화주사',
                'verbose_name_plural': '화주사',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='바코드')),
                ('width', models.FloatField(default=0, verbose_name='가로(cm)')),
                ('length', models.FloatField(default=0, verbose_name='세로(cm)')),
                ('height', models.FloatField(default=0, verbose_name='높이(cm)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='재고 수량')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.shipper', verbose_name='화주사')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
            },
        ),
    ]
