# Generated by Django 5.2.5 on 2025-09-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pallet_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='파렛트 수량'),
        ),
        migrations.AddField(
            model_name='product',
            name='products_per_pallet',
            field=models.PositiveIntegerField(default=0, verbose_name='파렛트 당 상품 수'),
        ),
    ]
