# Generated by Django 5.2.5 on 2025-10-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_pallet_quantity_product_products_per_pallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_size',
            field=models.CharField(choices=[('S', '소형'), ('M', '중형'), ('L', '대형'), ('XL', '특대형')], default='S', max_length=10, verbose_name='박스 크기'),
        ),
    ]
