# Generated by Django 5.2.5 on 2026-01-07 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_product_box_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='연락처'),
        ),
        migrations.CreateModel(
            name='ShipperApiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('COUPANG', '쿠팡 (Coupang)'), ('NAVER', '네이버 스마트스토어 (Naver)'), ('11ST', '11번가 (11st)')], max_length=20, verbose_name='쇼핑몰')),
                ('access_key', models.CharField(max_length=255, verbose_name='Access Key / Client ID')),
                ('secret_key', models.CharField(max_length=255, verbose_name='Secret Key / Client Secret')),
                ('extra_info', models.TextField(blank=True, default='{}', verbose_name='추가 정보(JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_infos', to='management.shipper', verbose_name='화주사')),
            ],
            options={
                'verbose_name': '화주사 API 정보',
                'verbose_name_plural': '화주사 API 정보 목록',
                'unique_together': {('shipper', 'channel_type')},
            },
        ),
    ]
