# Generated by Django 5.2.5 on 2026-01-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_shipper_address_alter_shipper_contact_shipperapiinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipperapiinfo',
            name='channel_type',
            field=models.CharField(choices=[('COUPANG', '쿠팡 (Coupang)'), ('NAVER', '네이버 스마트스토어 (Naver SmartStore)'), ('11ST', '11번가 (11st)'), ('GMARKET', 'G마켓 (Gmarket)'), ('AUCTION', '옥션 (Auction)'), ('WEMAKEPRICE', '위메프 (WeMakePrice)'), ('TMON', '티몬 (TMON)'), ('INTERPARK', '인터파크 (Interpark)')], max_length=20, verbose_name='쇼핑몰'),
        ),
    ]
