# Generated by Django 5.2.4 on 2025-08-06 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='센터명')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='택배사명')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='연락처')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='주문날짜')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='배송날짜')),
                ('order_status', models.CharField(choices=[('준비중', '준비중'), ('완료', '완료'), ('취소', '취소')], default='준비중', max_length=10)),
                ('delivery_status', models.CharField(blank=True, choices=[('집하완료', '집하완료'), ('배송중', '배송중'), ('배송완료', '배송완료')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='화주사명')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='담당자')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_app.center', verbose_name='소속 센터')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='바코드')),
                ('width', models.FloatField(default=0, verbose_name='가로(cm)')),
                ('length', models.FloatField(default=0, verbose_name='세로(cm)')),
                ('height', models.FloatField(default=0, verbose_name='높이(cm)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='재고 수량')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_app.shipper', verbose_name='화주사')),
            ],
        ),
    ]
