# Generated by Django 5.2.5 on 2025-08-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='오류 메시지'),
        ),
    ]
