# Generated by Django 5.2.4 on 2025-08-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', '입고'), ('OUT', '출고')], max_length=3, verbose_name='구분')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_app.product', verbose_name='상품')),
            ],
        ),
    ]
