# Generated by Django 5.2.5 on 2025-08-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0002_order_error_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
