# Generated by Django 5.2.5 on 2025-09-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='주문번호')),
                ('order_date', models.DateTimeField(verbose_name='주문일시')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='수취인명')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='우편번호')),
                ('order_status', models.CharField(choices=[('PENDING', '주문접수'), ('PROCESSING', '처리중'), ('SHIPPED', '출고완료'), ('DELIVERED', '배송완료'), ('CANCELED', '주문취소'), ('ERROR', '오류')], default='PENDING', max_length=20, verbose_name='주문 상태')),
                ('delivery_memo', models.TextField(blank=True, verbose_name='배송 메모')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.saleschannel', verbose_name='판매 채널')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.shipper', verbose_name='화주사')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품',
            },
        ),
    ]
