# Generated by Django 5.2.5 on 2026-01-08 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_shipper_address_alter_shipper_contact_shipperapiinfo'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(max_length=20, verbose_name='쇼핑몰')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집 시각')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('PARTIAL', '부분 성공'), ('FAILED', '실패')], default='SUCCESS', max_length=20, verbose_name='상태')),
                ('total_count', models.IntegerField(default=0, verbose_name='총 주문 수')),
                ('success_count', models.IntegerField(default=0, verbose_name='성공 건수')),
                ('error_count', models.IntegerField(default=0, verbose_name='실패 건수')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.shipper', verbose_name='화주사')),
            ],
            options={
                'verbose_name': 'API 수집 로그',
                'verbose_name_plural': 'API 수집 로그',
                'ordering': ['-collected_at'],
            },
        ),
    ]
